services:
  db:
    container_name: db
    build:
      context: ./containers/db
      dockerfile: Dockerfile
      args:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
#    ports:
#      - "42422:5432"
    networks:
      - transcendence
    volumes:
      - db_volume:/var/lib/postgresql/data

  django:
    container_name: django
    secrets:
      - secret_key
      - oauth2_client_id
      - oauth2_client_secret
      - sepolia_url
      - private_key
      - contract_address
      - postgres_user
      - postgres_password
    build:
      context: ./containers/django
      dockerfile: Dockerfile
    environment:
      SECRET_KEY: /run/secrets/secret_key
      OAUTH2_CLIENT_ID: /run/secrets/oauth2_client_id
      OAUTH2_CLIENT_SECRET: /run/secrets/oauth2_client_secret
      SEPOLIA_URL: /run/secrets/sepolia_url
      PRIVATE_KEY: /run/secrets/private_key
      CONTRACT_ADDRESS: /run/secrets/contract_address
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    depends_on:
      - db
    expose:
      - 8000
    env_file:
      - .env
    networks:
      - transcendence
    volumes:
      - static_volume:/var/static
      - media_volume:/var/media

  nginx:
    container_name: nginx
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile
    depends_on:
      - django
    ports:
      - "42443:443"
    networks:
      - transcendence
    volumes:
      - static_volume:/var/static
      - media_volume:/var/media

networks:
  transcendence:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  db_volume:

secrets:
  contract_address:
    file: ./secrets/contract_address
  oauth2_client_secret:
    file: ./secrets/oauth2_client_secret
  postgres_admin_user:
    file: ./secrets/postgres_admin_user
  postgres_user:
    file: ./secrets/postgres_user
  sepolia_url:
    file: ./secrets/sepolia_url
  oauth2_client_id:
    file: ./secrets/oauth2_client_id
  postgres_admin_password:
    file: ./secrets/postgres_admin_password
  postgres_password:
    file: ./secrets/postgres_password
  private_key:
    file: ./secrets/private_key
  secret_key:
    file: ./secrets/secret_key
