# Generated by Django 4.2.11 on 2024-05-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_transcendence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='friendlist',
            field=models.ManyToManyField(blank=True, related_name='friends', to='mini_transcendence.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='records',
            field=models.ManyToManyField(blank=True, related_name='players', to='mini_transcendence.gamerecord'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game_records', models.ManyToManyField(related_name='tournaments', to='mini_transcendence.gamerecord')),
            ],
        ),
    ]
