# Generated by Django 4.2.11 on 2024-05-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_transcendence', '0003_gamerecord_creation_time_player_creation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='creation_time',
        ),
    ]
