# Generated by Django 4.2.11 on 2024-05-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_transcendence', '0004_remove_player_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
