# Generated by Django 4.2.11 on 2024-05-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_transcendence', '0006_player_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default='assets/avatars/default.jpg', upload_to='assets/avatars/'),
        ),
    ]
