# Generated by Django 4.2.11 on 2024-06-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_transcendence', '0007_alter_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='intra_login',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
