# Generated by Django 4.2.11 on 2024-06-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_transcendence', '0008_player_intra_login_alter_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='intra_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
