# Generated by Django 4.2.11 on 2024-06-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_pageview'),
        ('mini_transcendence', '0009_player_intra_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='players', to='chat.room'),
        ),
    ]
