# Generated by Django 4.2.11 on 2024-06-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_remove_message_room'),
        ('mini_transcendence', '0010_player_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rooms',
        ),
        migrations.AddField(
            model_name='player',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='players', to='chat.chat'),
        ),
    ]
