# Generated by Django 4.2.11 on 2024-06-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_transcendence', '0012_remove_player_chats_player_group_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='group_chats',
        ),
    ]
