# Generated by Django 4.2.11 on 2024-06-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_transcendence', '0013_remove_player_group_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='blocklist',
            field=models.ManyToManyField(blank=True, related_name='blocked_players', to='mini_transcendence.player'),
        ),
    ]
