# Generated by Django 4.2.11 on 2024-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('mini_transcendence', '0014_player_blocklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='records',
            field=models.ManyToManyField(blank=True, related_name='players', to='game.gamerecord'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game_records',
            field=models.ManyToManyField(related_name='tournaments', to='game.gamerecord'),
        ),
        migrations.DeleteModel(
            name='GameRecord',
        ),
    ]
