# Generated by Django 4.2.11 on 2024-06-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_transcendence', '0015_alter_player_records_alter_tournament_game_records_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
