"""
Django settings for simplified_prj project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path


def read_secret(secret_path):
    with open(secret_path, 'r') as file:
        return file.read().strip()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = read_secret('/run/secrets/secret_key')

SECURE_CONTENT_TYPE_NOSNIFF = False

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Redirect all HTTP traffic to HTTPS
SECURE_SSL_REDIRECT = True

# Enable Secure Proxy SSL Header
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ALLOWED_HOSTS = ['made-f0Br7s7.clusters.42paris.fr']

CSRF_TRUSTED_ORIGINS = [
    'https://made-f0Br7s7.clusters.42paris.fr',
    'https://made-f0Br7s7.clusters.42paris.fr:42443'
]

CSRF_ALLOWED_ORIGINS = [
    'https://made-f0Br7s7.clusters.42paris.fr',
    'https://made-f0Br7s7.clusters.42paris.fr:42443'
]
CORS_ORIGINS_WHITELIST = [
    'https://made-f0Br7s7.clusters.42paris.fr',
    'https://made-f0Br7s7.clusters.42paris.fr:42443'
]

# Application definition

INSTALLED_APPS = [
    'channels',
    'requests',
    'bootstrap5',
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'mini_transcendence',
    'chat',
    'game',
]

ASGI_APPLICATION = 'simplified_prj.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'chat.middleware.PageViewMiddleware',
    'mini_transcendence.middleware.DisableClientSideCachingMiddleware',
    'mini_transcendence.middleware.OnlineUserMiddleware',
]

ROOT_URLCONF = 'simplified_prj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'simplified_prj.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

POSTGRES_USER = read_secret('/run/secrets/postgres_user')
POSTGRES_PASSWORD = read_secret('/run/secrets/postgres_password')
POSTGRES_DB = os.getenv('POSTGRES_DB', None)
POSTGRES_HOST = os.getenv('POSTGRES_HOST', None)
POSTGRES_PORT = os.getenv('POSTGRES_PORT', None)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES_DB,
        'USER': POSTGRES_USER,
        'HOST': POSTGRES_HOST,
        'PASSWORD': POSTGRES_PASSWORD,
        'PORT': POSTGRES_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = os.getenv('STATIC_URL', None)
STATIC_ROOT = os.getenv('STATIC_ROOT', None)
MEDIA_URL = os.getenv('MEDIA_URL', None)
MEDIA_ROOT = os.getenv('MEDIA_ROOT', None)

INTRA_REDIRECT_LINK = os.getenv('INTRA_REDIRECT_LINK', None)
OAUTH2_CLIENT_ID = read_secret('/run/secrets/oauth2_client_id')
OAUTH2_CLIENT_SECRET = read_secret('/run/secrets/oauth2_client_secret')
OAUTH2_TOKEN_URL = os.getenv('OAUTH2_TOKEN_URL', None)
OAUTH2_AUTH_URL = os.getenv('OAUTH2_AUTH_URL', None)
OAUTH2_MY_DATA_URL = os.getenv('OAUTH2_MY_DATA_URL', None)
OAUTH2_TOKEN_INFO_URL = os.getenv('OAUTH2_TOKEN_INFO_URL', None)
SEPOLIA_URL = read_secret('/run/secrets/sepolia_url')
PRIVATE_KEY = read_secret('/run/secrets/private_key')
CONTRACT_ADDRESS = read_secret('/run/secrets/contract_address')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_TZ = True
