# Generated by Django 4.2.11 on 2024-06-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_transcendence', '0013_remove_player_group_chats'),
        ('chat', '0007_groupchat_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='blocked_players',
            field=models.ManyToManyField(blank=True, related_name='blocked_in_group_chats', to='mini_transcendence.player'),
        ),
    ]
