# Generated by Django 4.2.11 on 2024-06-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_groupchat_blocked_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogue',
            name='player1_blocked',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='player2_blocked',
        ),
    ]
