# Generated by Django 4.2.11 on 2024-06-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_dialogue_player1_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='actions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='message', max_length=20),
        ),
    ]
