# Generated by Django 4.2.11 on 2024-06-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
