# Generated by Django 4.2.11 on 2024-07-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_transcendence', '0016_delete_tournament'),
        ('game', '0006_gamerecord_hash_alter_tournamentrecord_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentrecord',
            name='game_records',
        ),
        migrations.AlterField(
            model_name='tournamentrecord',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TournamentPlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('tournament_alias', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_stats', to='mini_transcendence.player')),
                ('records', models.ManyToManyField(blank=True, related_name='tournament_stats', to='game.gamerecord')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='game.tournamentrecord')),
            ],
        ),
    ]
